- name: Create group in Hoop Identity
  ansible.builtin.uri:
    url: "{{ hoop_api_base_url }}/users/groups"
    method: POST
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ hoop_token }}"
    body_format: json
    body:
      name: "{{ hoop_group_name }}"
    status_code: [200, 201]
  register: group_creation_result

- name: Create user in Hoop Identity
  ansible.builtin.uri:
    url: "{{ hoop_api_base_url }}/users"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      email: "{{ hoop_user_email }}"
      groups: "{{ hoop_user_groups }}"
      name: "{{ hoop_user_name }}"
      password: "{{ hoop_user_password }}"
    status_code: [200, 201]
  register: user_creation_result
